const assert = require('node:assert/strict'); const { before, after, describe, test } = require('node:test'); const express = require('express');
const { buildClipCaptions, captionTimestamp, normalizeCaptionText, serializeCaptions } = require('../dist/domains/captions');
const { ClipRenderService, RenderError } = require('../dist/services/rendering');
const { createRenderRouter } = require('../dist/routes/renders');
const segment = (id, startMs, endMs, text, position = 0) => ({ id, startMs, endMs, text, position });

describe('Clip caption temporal export domain', () => {
  test('shifts genuine overlapping source intervals to clip zero', () => { const result = buildClipCaptions([segment('first', 1000, 3000, 'Inicio'), segment('second', 3000, 5000, 'Fim', 1)], 1000, 5000); assert.deepEqual(result.cues.map(({ startMs, endMs }) => [startMs, endMs]), [[0, 2000], [2000, 4000]]); assert.equal(result.durationMs, 4000); assert.equal(result.cues[1].sourceSegmentId, 'second'); });
  test('clamps partial segments and explicitly warns that full text remains', () => { const result = buildClipCaptions([segment('wide', 0, 5000, 'A frase completa permanece.')], 1000, 3000); assert.deepEqual(result.cues[0], { index: 1, startMs: 0, endMs: 2000, text: 'A frase completa permanece.', sourceSegmentId: 'wide' }); assert.ok(result.warnings.some((warning) => warning.includes('Segmento parcial'))); });
  test('preserves temporal overlap instead of inventing nonoverlapping timestamps', () => { const result = buildClipCaptions([segment('a', 1000, 3000, 'A'), segment('b', 2000, 4000, 'B', 1)], 0, 5000); assert.equal(result.cues[1].startMs, 2000); assert.ok(result.warnings.some((warning) => warning.includes('sobrepostos'))); });
  test('ordering is deterministic and input is not mutated', () => { const source = [segment('b', 2000, 3000, 'B', 2), segment('a', 2000, 2500, 'A', 1), segment('zero', 0, 1000, 'Z')]; const before = structuredClone(source); assert.deepEqual(buildClipCaptions(source, 0, 4000).cues.map(({ sourceSegmentId }) => sourceSegmentId), ['zero', 'a', 'b']); assert.deepEqual(source, before); });
  test('Unicode and genuine multiline text survive blank-line and control normalization', () => { const result = normalizeCaptionText('  Ação 🚙 日本語\r\n\r\nVitória\u0000!\r\n'); assert.equal(result, 'Ação 🚙 日本語\nVitória!'); });
  test('serializers neutralize markup and cue injection while preserving visible text', () => { const { cues } = buildClipCaptions([segment('x', 0, 2000, '<b>Ação & vitória</b>\n\n00:00:01.000 --> 00:00:02.000\ntexto')], 0, 2000); for (const format of ['srt', 'vtt']) { const text = serializeCaptions(cues, format); assert.match(text, /&lt;b&gt;Ação &amp; vitória&lt;\/b&gt;/); assert.equal((text.match(/ --> /g) || []).length, 1); assert.match(text, /--&gt;/); assert.ok(!text.includes('<b>')); } });
  test('SRT uses comma, VTT uses dot and hours never wrap', () => { assert.equal(captionTimestamp(3661007, ','), '01:01:01,007'); assert.equal(captionTimestamp(360000000, '.'), '100:00:00.000'); const cue = { index: 1, startMs: 0, endMs: 1234, text: 'Olá', sourceSegmentId: 'x' }; assert.match(serializeCaptions([cue], 'srt'), /00:00:01,234/); assert.ok(serializeCaptions([cue], 'vtt').startsWith('WEBVTT\n\n1\n00:00:00.000 --> 00:00:01.234')); });
  test('boundary-touching and empty-text segments do not create fabricated cues', () => { const result = buildClipCaptions([segment('before', 0, 1000, 'antes'), segment('after', 3000, 4000, 'depois'), segment('empty', 1000, 2000, '\u0000\n ')], 1000, 3000); assert.deepEqual(result.cues, []); assert.ok(result.warnings.length); });
  test('invalid clip timestamps are rejected and invalid segments are explicitly omitted', () => { assert.throws(() => buildClipCaptions([], 2, 1)); assert.throws(() => captionTimestamp(Infinity, '.')); const result = buildClipCaptions([segment('bad', -1, 1000, 'erro')], 0, 2000); assert.equal(result.cues.length, 0); assert.match(result.warnings[0], /invalido/); });
});

describe('Caption HTTP download contracts', () => {
  let server; let url;
  const populated = { jobId: 'job1', available: true, reasons: [], cueCount: 1, durationMs: 2000, cues: [{ index: 1, startMs: 0, endMs: 2000, text: 'Ação & vitória 🚙', sourceSegmentId: 'source1' }], formats: ['srt', 'vtt'], warnings: [] };
  before(async () => { const service = { captions: async (id) => { if (id === 'stale') throw new RenderError('OUTPUT_OUTDATED', 'Resultado desatualizado.'); if (id === 'missing') throw new RenderError('NOT_FOUND', 'Nao encontrado.', 404); return id === 'empty' ? { ...populated, jobId: id, available: false, cues: [], cueCount: 0, reasons: ['Sem segmentos.'] } : populated; }, captionFile: function(id, format) { return ClipRenderService.prototype.captionFile.call(this, id, format); } }; const app = express(); app.use('/api/renders', createRenderRouter(service)); server = await new Promise((resolve) => { const value = app.listen(0, '127.0.0.1', () => resolve(value)); }); url = `http://127.0.0.1:${server.address().port}/api/renders/jobs`; });
  after(async () => { await new Promise((resolve) => server.close(resolve)); });
  test('JSON preview and UTF8 SRT/VTT downloads use safe attachment headers', async () => { const json = await fetch(`${url}/job1/captions`); assert.equal((await json.json()).cues[0].text, populated.cues[0].text); for (const format of ['srt', 'vtt']) { const response = await fetch(`${url}/job1/captions/${format}`); assert.equal(response.status, 200); assert.equal(response.headers.get('content-disposition'), `attachment; filename="job1.${format}"`); assert.match(response.headers.get('content-type'), /charset=utf-8/i); assert.equal(response.headers.get('x-content-type-options'), 'nosniff'); assert.match(await response.text(), /Ação &amp; vitória 🚙/); } });
  test('HEAD has no body and invalid format/query are strict', async () => { const head = await fetch(`${url}/job1/captions/srt`, { method: 'HEAD' }); assert.equal(head.status, 200); assert.equal((await head.arrayBuffer()).byteLength, 0); assert.equal((await fetch(`${url}/job1/captions/ass`)).status, 400); assert.equal((await fetch(`${url}/job1/captions?unknown=x`)).status, 400); assert.equal((await fetch(`${url}/job1/captions/vtt?unknown=x`)).status, 400); });
  test('empty transcript reports absence and stale/empty downloads are blocked', async () => { assert.equal((await (await fetch(`${url}/empty/captions`)).json()).available, false); assert.equal((await fetch(`${url}/empty/captions/srt`)).status, 409); assert.equal((await fetch(`${url}/stale/captions`)).status, 409); assert.equal((await fetch(`${url}/missing/captions`)).status, 404); });
});
