const assert = require('node:assert/strict'); const { before, after, beforeEach, describe, test } = require('node:test');
const fs = require('node:fs'); const path = require('node:path'); const os = require('node:os'); const { execFileSync } = require('node:child_process'); const express = require('express');
process.env.DATABASE_URL = ':memory:';
const { DatabaseService } = require('../dist/database/DatabaseService');
const { MediaFiles, MediaProbe, MediaSourceService } = require('../dist/services/media');
const { ProductionService } = require('../dist/services/production'); const { ProductionRepository } = require('../dist/database/repositories/ProductionRepository');
const { ChaptersService } = require('../dist/services/chapters'); const { ChapterRepository } = require('../dist/database/repositories/ChapterRepository');
const { ShortsService } = require('../dist/services/shorts'); const { ShortsRepository } = require('../dist/database/repositories/ShortsRepository');
const { ClipRenderService, createRenderRunner, renderArguments, RenderError } = require('../dist/services/rendering');
const { createRenderRouter } = require('../dist/routes/renders');
const { EventEmitter } = require('node:events');

describe('FFmpeg process lifecycle guards', () => {
  const childFactory = (onStart) => { let child; return { get child() { return child; }, spawn: (_exe, _args, options) => { assert.equal(options.shell, false); assert.equal(options.windowsHide, true); child = new EventEmitter(); child.stdout = new EventEmitter(); child.stderr = new EventEmitter(); child.killed = false; child.kill = () => { child.killed = true; queueMicrotask(() => child.emit('close', null)); }; setImmediate(() => onStart?.(child)); return child; } }; };
  const input = (signal) => ({ sourcePath: 'source.mp4', outputPath: 'output.mp4', startMs: 0, endMs: 5000, layout: 'FIT', signal, onProgress: (value) => assert.ok(value >= 0 && value <= 95) });
  test('actual wrapper timeout kills the child and rejects after process close', async () => { const factory = childFactory(); await assert.rejects(() => createRenderRunner('ffmpeg', 10, factory.spawn)(input(new AbortController().signal)), (error) => error.code === 'RENDER_TIMEOUT'); assert.equal(factory.child.killed, true); });
  test('actual wrapper abort and total short-line stdout cap kill the child', async () => { const controller = new AbortController(); const aborted = childFactory(() => controller.abort()); await assert.rejects(() => createRenderRunner('ffmpeg', 1000, aborted.spawn)(input(controller.signal)), (error) => error.code === 'CANCELLED'); assert.equal(aborted.child.killed, true); const excessive = childFactory((child) => { const chunk = Buffer.from('out_time_us=1000\n'.repeat(300)); for (let index = 0; index < 200 && !child.killed; index++) child.stdout.emit('data', chunk); }); await assert.rejects(() => createRenderRunner('ffmpeg', 1000, excessive.spawn)(input(new AbortController().signal)), (error) => error.code === 'RENDER_OUTPUT_LIMIT'); assert.equal(excessive.child.killed, true); });
});

describe('Controlled local clip rendering', { concurrency: false }, () => {
  let client; let temp; let root; let output; let fixture; let files; let media; let production; let chapters; let shorts; let renderer; let rootId; let server; let url; const instances = [];
  const makeRenderer = (runner) => { const value = new ClipRenderService(client, files, new MediaProbe(), runner, output); instances.push(value); return value; };
  before(async () => {
    temp = fs.mkdtempSync(path.join(os.tmpdir(), 'jvitorz-render-test-')); root = path.join(temp, 'sources'); output = path.join(temp, 'outputs'); fs.mkdirSync(root); fixture = path.join(root, 'fixture.mp4');
    execFileSync('ffmpeg', ['-hide_banner', '-loglevel', 'error', '-f', 'lavfi', '-i', 'color=c=blue:s=160x90:d=6', '-f', 'lavfi', '-i', 'sine=frequency=440:duration=6', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-shortest', '-y', fixture], { windowsHide: true, timeout: 20000, stdio: 'pipe' });
    client = await DatabaseService.connect(); for (const directory of fs.readdirSync(path.resolve(__dirname, '../prisma/migrations')).sort()) { const file = path.resolve(__dirname, '../prisma/migrations', directory, 'migration.sql'); if (!fs.existsSync(file)) continue; for (const statement of fs.readFileSync(file, 'utf8').split(';').map((part) => part.replace(/^--.*$/gm, '').trim()).filter(Boolean)) await client.$executeRawUnsafe(statement); }
    await client.$executeRawUnsafe('PRAGMA foreign_keys = ON'); files = new MediaFiles([root]); rootId = (await files.roots())[0].id; production = new ProductionService(new ProductionRepository(client)); media = new MediaSourceService(client, files, new MediaProbe(), production); chapters = new ChaptersService(new ChapterRepository(client), production); shorts = new ShortsService(new ShortsRepository(client), production, { resolve: async () => ({ entries: [] }) }); renderer = makeRenderer(); await renderer.initialize();
    const app = express(); app.use(express.json()); app.use('/api/renders', createRenderRouter(renderer)); server = await new Promise((resolve) => { const value = app.listen(0, '127.0.0.1', () => resolve(value)); }); url = `http://127.0.0.1:${server.address().port}/api/renders`;
  });
  after(async () => { for (const instance of instances) await instance.waitForIdle(); await new Promise((resolve) => server.close(resolve)); await DatabaseService.disconnect(); const resolved = path.resolve(temp); assert.ok(resolved.startsWith(path.resolve(os.tmpdir()) + path.sep) && path.basename(resolved).startsWith('jvitorz-render-test-')); fs.rmSync(resolved, { recursive: true, force: true }); });
  beforeEach(async () => { for (const instance of instances) await instance.waitForIdle(); await client.clipRenderJob.deleteMany(); await client.shortAnalysis.deleteMany(); await client.chapterSet.deleteMany(); await client.timedTranscript.deleteMany(); await client.contentProduction.deleteMany(); await client.localMediaSource.deleteMany(); await client.libraryItem.deleteMany(); });
  const ready = async (complete = true, sourceFile = 'fixture.mp4') => {
    const { production: row } = await production.create({ productionKey: 'render', title: 'Render fixture' }); const { source } = await media.register({ rootId, relativePath: sourceFile, productionId: row.id, role: 'EDITED_VIDEO' });
    for (const key of ['PREPARING', 'EDITING']) { await production.startStep(row.id, key); await production.completeStep(row.id, key); }
    await chapters.importTranscript({ productionId: row.id, format: 'INTERNAL', segments: [{ startMs: 1000, endMs: 3000, text: 'Vamos tentar passar pela ponte.' }, { startMs: 3000, endMs: 5000, text: 'Consegui finalmente chegar ao outro lado!' }, { startMs: 5000, endMs: 6000, text: 'Pronto, acabou o desafio.' }] });
    await production.skipStep(row.id, 'CHAPTERS', { reason: 'Fixture isolada' }); const { analysis } = await shorts.analyze(row.id); const candidate = await shorts.setStatus(analysis.candidates[0].id, 'SELECTED'); if (complete) await shorts.complete(analysis.id); return { row, source, candidate, analysis };
  };
  const request = async (route, method = 'GET', body) => { const response = await fetch(`${url}${route}`, { method, headers: { 'content-type': 'application/json' }, ...(body !== undefined ? { body: JSON.stringify(body) } : {}) }); return { status: response.status, body: await response.json() }; };
  test('FIT preserves whole image and CENTER_CROP is explicit in fixed profiles', () => { const input = { sourcePath: 'input.mp4', outputPath: 'output.mp4', startMs: 1000, endMs: 6000, signal: new AbortController().signal, onProgress: () => {} }; const fit = renderArguments({ ...input, layout: 'FIT' }); assert.ok(fit.includes('-n')); assert.ok(fit.some((value) => value.includes('pad=720:1280'))); assert.ok(renderArguments({ ...input, layout: 'CENTER_CROP' }).some((value) => value.includes('crop=720:1280'))); assert.equal(fit[fit.indexOf('-protocol_whitelist') + 1], 'file'); assert.equal(fit[fit.indexOf('-t') + 1], '5.000'); });
  test('read-only preflight uses same registered asset and completed selected handoff', async () => { const { candidate, source } = await ready(); const before = await client.productionEvent.count(); const result = await renderer.preflight(candidate.id); assert.equal(result.eligible, true); assert.equal(result.source.id, source.id); assert.equal(result.clip.startMs, 1000); assert.equal(result.defaultLayout, 'FIT'); assert.equal(await client.productionEvent.count(), before); assert.equal(await client.clipRenderJob.count(), 0); });
  test('preflight blocks uncompleted Shorts and unselected candidates', async () => { const { candidate } = await ready(false); assert.equal((await renderer.preflight(candidate.id)).eligible, false); await shorts.setStatus(candidate.id, 'REJECTED'); await assert.rejects(() => renderer.enqueue({ candidateId: candidate.id }), /Selecione/); });
  test('preflight rejects an asset without registry rather than choosing another source', async () => { const { row, candidate } = await ready(); const item = await client.libraryItem.create({ data: { title: 'Outro video', type: 'video' } }); await production.linkAsset(row.id, item.id, 'EDITED_VIDEO'); const result = await renderer.preflight(candidate.id); assert.equal(result.eligible, false); assert.equal(result.source, null); });
  test('real FIT rendering validates 720x1280 H264 AAC duration and Library output', async () => { const { candidate } = await ready(); const sourceBytes = fs.readFileSync(fixture); const result = await renderer.enqueue({ candidateId: candidate.id }); await renderer.waitForIdle(); const job = await renderer.get(result.job.id); assert.equal(job.status, 'SUCCEEDED', job.errorMessage); assert.equal(job.progress, 100); assert.equal(job.outputMetadata.width, 720); assert.equal(job.outputMetadata.height, 1280); assert.equal(job.outputMetadata.videoCodec, 'h264'); assert.equal(job.outputMetadata.audioCodec, 'aac'); assert.ok(Math.abs(job.outputMetadata.durationMs - 5000) <= 350); assert.ok(job.outputLibraryItemId); assert.equal(await client.libraryItem.count(), 2); assert.deepEqual(fs.readFileSync(fixture), sourceBytes); assert.ok(!JSON.stringify(job).includes(temp.replace(/\\/g, '\\\\'))); });
  test('duplicate concurrent enqueue creates one job per snapshot', async () => { const { candidate } = await ready(); const results = await Promise.all([renderer.enqueue({ candidateId: candidate.id }), renderer.enqueue({ candidateId: candidate.id })]); await renderer.waitForIdle(); assert.equal(results[0].job.id, results[1].job.id); assert.equal(await client.clipRenderJob.count(), 1); assert.equal((await renderer.enqueue({ candidateId: candidate.id })).created, false); });
  test('real CENTER_CROP is a separate explicit job with validated dimensions', async () => { const { candidate } = await ready(); const result = await renderer.enqueue({ candidateId: candidate.id, layout: 'CENTER_CROP' }); await renderer.waitForIdle(); const job = await renderer.get(result.job.id); assert.equal(job.status, 'SUCCEEDED', job.errorMessage); assert.equal(job.layout, 'CENTER_CROP'); assert.equal(job.outputMetadata.width, 720); });
  test('worker is serial across distinct queued profiles', async () => { const { candidate } = await ready(); let active = 0; let peak = 0; const actual = createRenderRunner(); const serial = makeRenderer(async (input) => { active++; peak = Math.max(peak, active); try { await actual(input); } finally { active--; } }); await serial.initialize(); await Promise.all([serial.enqueue({ candidateId: candidate.id, layout: 'FIT' }), serial.enqueue({ candidateId: candidate.id, layout: 'CENTER_CROP' })]); await serial.waitForIdle(); assert.equal(peak, 1); assert.equal(await client.clipRenderJob.count({ where: { status: 'SUCCEEDED' } }), 2); });
  test('failure is persisted and retry creates a new explicit attempt', async () => { const { candidate } = await ready(); let fails = true; const actual = createRenderRunner(); const value = makeRenderer(async (input) => { if (fails) throw new RenderError('RENDER_FAILED', 'Falha controlada'); await actual(input); }); const result = await value.enqueue({ candidateId: candidate.id }); await value.waitForIdle(); assert.equal((await value.get(result.job.id)).status, 'FAILED'); assert.equal((await value.enqueue({ candidateId: candidate.id })).created, false); fails = false; const retry = await value.retry(result.job.id); await value.waitForIdle(); assert.equal(retry.job.attempt, 2); assert.notEqual(retry.job.id, result.job.id); assert.equal((await value.get(retry.job.id)).status, 'SUCCEEDED'); });
  test('running cancellation aborts process and never publishes Library output', async () => { const { candidate } = await ready(); let entered; const running = new Promise((resolve) => { entered = resolve; }); const value = makeRenderer((input) => new Promise((_resolve, reject) => { entered(); input.signal.addEventListener('abort', () => reject(new RenderError('CANCELLED', 'Cancelado')), { once: true }); })); const { job } = await value.enqueue({ candidateId: candidate.id }); await running; assert.equal((await value.cancel(job.id)).status, 'CANCELLED'); await value.waitForIdle(); assert.equal((await value.get(job.id)).outputLibraryItemId, null); assert.equal((await value.cancel(job.id)).status, 'CANCELLED'); });
  test('cancellation in the claim-before-controller window never starts FFmpeg', async () => { const { candidate } = await ready(); let release; let seen; const gate = new Promise((resolve) => { release = resolve; }); const claimed = new Promise((resolve) => { seen = resolve; }); const jobs = new Proxy(client.clipRenderJob, { get(target, key) { if (key === 'updateMany') return async (args) => { const result = await target.updateMany(args); if (args.where?.status === 'QUEUED' && args.data?.status === 'RUNNING') { seen(); await gate; } return result; }; const value = target[key]; return typeof value === 'function' ? value.bind(target) : value; } }); const wrapped = new Proxy(client, { get(target, key) { if (key === 'clipRenderJob') return jobs; const value = target[key]; return typeof value === 'function' ? value.bind(target) : value; } }); let calls = 0; const value = new ClipRenderService(wrapped, files, new MediaProbe(), async () => { calls++; }, output); instances.push(value); const { job } = await value.enqueue({ candidateId: candidate.id }); await claimed; await value.cancel(job.id); release(); await value.waitForIdle(); assert.equal(calls, 0); assert.equal((await value.get(job.id)).status, 'CANCELLED'); });
  test('process restart marks unfinished jobs INTERRUPTED without restarting them', async () => { const { candidate, analysis, row, source } = await ready(); const job = await client.clipRenderJob.create({ data: { id: 'restart-job', candidateId: candidate.id, analysisId: analysis.id, productionId: row.id, sourceId: source.id, snapshotKey: 'restart', snapshot: {}, layout: 'FIT', status: 'RUNNING' } }); let calls = 0; const restarted = makeRenderer(async () => { calls++; }); await restarted.initialize(); assert.equal((await restarted.get(job.id)).status, 'INTERRUPTED'); assert.equal(calls, 0); });
  test('unused renderer shutdown touches neither database nor output directory', async () => { let reads = 0; const unusedClient = new Proxy({}, { get() { reads++; throw new Error('Database must remain untouched'); } }); const unusedRoot = path.join(temp, 'unused-renderer'); const unused = new ClipRenderService(unusedClient, files, new MediaProbe(), createRenderRunner(), unusedRoot); await unused.shutdown(); await unused.shutdown(); assert.equal(reads, 0); assert.equal(fs.existsSync(unusedRoot), false); await assert.rejects(() => unused.enqueue({ candidateId: 'candidate' }), (error) => error.code === 'APPLICATION_STOPPED' && error.httpStatus === 409); });
  test('shutdown aborts active rendering and interrupts queued jobs without running them', async () => { const { candidate } = await ready(); let entered; let calls = 0; let aborted = false; const started = new Promise((resolve) => { entered = resolve; }); const value = makeRenderer((input) => new Promise((_resolve, reject) => { calls++; entered(); input.signal.addEventListener('abort', () => { aborted = true; reject(new RenderError('CANCELLED', 'Encerrando')); }, { once: true }); })); const first = await value.enqueue({ candidateId: candidate.id }); await started; const second = await value.enqueue({ candidateId: candidate.id, layout: 'CENTER_CROP' }); await value.shutdown(); assert.equal(aborted, true); assert.equal(calls, 1); for (const jobId of [first.job.id, second.job.id]) { const job = await client.clipRenderJob.findUnique({ where: { id: jobId } }); assert.equal(job.status, 'INTERRUPTED'); assert.equal(job.errorCode, 'APPLICATION_STOPPED'); assert.equal(job.outputLibraryItemId, null); } await assert.rejects(() => value.enqueue({ candidateId: candidate.id }), (error) => error.code === 'APPLICATION_STOPPED'); });
  test('shutdown waits for in-flight enqueue validation and prevents late job creation', async () => { const { candidate } = await ready(); let entered; let release; const seen = new Promise((resolve) => { entered = resolve; }); const gate = new Promise((resolve) => { release = resolve; }); const delayed = new MediaFiles([root]); const resolve = delayed.resolve.bind(delayed); delayed.resolve = async (...args) => { const file = await resolve(...args); entered(); await gate; return file; }; const value = new ClipRenderService(client, delayed, new MediaProbe(), createRenderRunner(), output); instances.push(value); await value.initialize(); const enqueue = value.enqueue({ candidateId: candidate.id }); const rejected = assert.rejects(() => enqueue, (error) => error.code === 'APPLICATION_STOPPED'); await seen; const stopping = value.shutdown(); release(); await Promise.all([rejected, stopping]); assert.equal(await client.clipRenderJob.count(), 0); });
  test('database worker failure stops once without an automatic retry loop', async () => { let calls = 0; let counts = 0; const fakeClient = { clipRenderJob: { updateMany: async () => ({ count: 1 }), findFirst: async () => { calls++; throw new Error('database unavailable'); }, count: async () => { counts++; return 1; } } }; const stopped = new ClipRenderService(fakeClient, files, new MediaProbe(), createRenderRunner(), output); await stopped.initialize(); stopped.kick(); await stopped.waitForIdle(); assert.equal(calls, 1); assert.equal(counts, 0); assert.equal((await stopped.health()).available, false); await assert.rejects(() => stopped.enqueue({ candidateId: 'candidate' }), (error) => error.code === 'WORKER_STOPPED'); });
  test('candidate change during render invalidates output before success', async () => { const { candidate } = await ready(); const actual = createRenderRunner(); const value = makeRenderer(async (input) => { await actual(input); await shorts.editCandidate(candidate.id, { title: 'Alterado durante render' }); }); const { job } = await value.enqueue({ candidateId: candidate.id }); await value.waitForIdle(); const result = await value.get(job.id); assert.equal(result.status, 'FAILED'); assert.equal(result.errorCode, 'SOURCE_CHANGED'); assert.equal(result.outputLibraryItemId, null); });
  test('candidate change after success blocks old preview and preserves output reference', async () => { const { candidate } = await ready(); const { job } = await renderer.enqueue({ candidateId: candidate.id }); await renderer.waitForIdle(); const before = await renderer.get(job.id); await shorts.editCandidate(candidate.id, { title: 'Alterado depois' }); const after = await renderer.get(job.id); assert.equal(after.status, 'FAILED'); assert.equal(after.errorCode, 'OUTPUT_OUTDATED'); assert.equal(after.outputLibraryItemId, before.outputLibraryItemId); assert.equal(after.previewUrl, null); await assert.rejects(() => renderer.openPreview(job.id), /desatualizada/); });
  test('source mutation during render invalidates output even without registry refresh', async () => { const { candidate } = await ready(); const original = fs.readFileSync(fixture); const actual = createRenderRunner(); const value = makeRenderer(async (input) => { await actual(input); fs.appendFileSync(fixture, 'changed'); }); try { const { job } = await value.enqueue({ candidateId: candidate.id }); await value.waitForIdle(); assert.equal((await value.get(job.id)).errorCode, 'SOURCE_CHANGED'); } finally { fs.writeFileSync(fixture, original); } });
  test('invalid output metadata fails verification without Library output', async () => { const { candidate } = await ready(); const value = makeRenderer(async (input) => { fs.copyFileSync(fixture, input.outputPath); }); const { job } = await value.enqueue({ candidateId: candidate.id }); await value.waitForIdle(); assert.equal((await value.get(job.id)).errorCode, 'OUTPUT_INVALID'); assert.equal(await client.libraryItem.count(), 1); });
  test('video without source audio renders successfully without invented audio', async () => { const silent = path.join(root, 'silent.mp4'); execFileSync('ffmpeg', ['-hide_banner', '-loglevel', 'error', '-i', fixture, '-an', '-c:v', 'copy', '-y', silent], { windowsHide: true, timeout: 10000, stdio: 'pipe' }); const { candidate, source } = await ready(true, 'silent.mp4'); assert.equal(source.hasAudio, false); const { job } = await renderer.enqueue({ candidateId: candidate.id }); await renderer.waitForIdle(); const result = await renderer.get(job.id); assert.equal(result.status, 'SUCCEEDED', result.errorMessage); assert.equal(result.outputMetadata.hasAudio, false); assert.equal(result.outputMetadata.audioCodec, null); });
  test('dropping existing source audio fails output validation', async () => { const { candidate } = await ready(); const value = makeRenderer(async (input) => { const args = renderArguments(input); args.splice(args.length - 1, 0, '-an'); execFileSync('ffmpeg', args, { windowsHide: true, timeout: 15000, stdio: 'pipe' }); }); const { job } = await value.enqueue({ candidateId: candidate.id }); await value.waitForIdle(); assert.equal((await value.get(job.id)).errorCode, 'OUTPUT_INVALID'); });
  test('timeout and missing FFmpeg are persisted as explicit failures', async () => { const { candidate } = await ready(); const value = makeRenderer(async () => { throw new RenderError('RENDER_TIMEOUT', 'Tempo excedido'); }); const { job } = await value.enqueue({ candidateId: candidate.id }); await value.waitForIdle(); assert.equal((await value.get(job.id)).errorCode, 'RENDER_TIMEOUT'); const missing = makeRenderer(createRenderRunner('missing-jvitorz-ffmpeg')); const result = await missing.retry(job.id); await missing.waitForIdle(); assert.equal((await missing.get(result.job.id)).errorCode, 'RENDER_UNAVAILABLE'); });
  test('HTTP preflight enqueue list job preview Range HEAD and strict errors', async () => { const { row, candidate } = await ready(); assert.equal((await request(`/candidates/${candidate.id}/preflight`)).body.eligible, true); const response = await request('/jobs', 'POST', { candidateId: candidate.id }); assert.equal(response.status, 201); await renderer.waitForIdle(); const job = response.body.job; assert.equal((await request(`/jobs?productionId=${row.id}`)).body.length, 1); const preview = await fetch(`${url}/jobs/${job.id}/preview`, { headers: { Range: 'bytes=0-31' } }); assert.equal(preview.status, 206); assert.equal((await preview.arrayBuffer()).byteLength, 32); assert.equal((await fetch(`${url}/jobs/${job.id}/preview`, { method: 'HEAD' })).status, 200); assert.equal((await request('/jobs', 'POST', { candidateId: candidate.id, outputPath: 'secret.mp4' })).status, 400); assert.equal((await request('/jobs', 'POST', { candidateId: candidate.id, layout: 'OTHER' })).status, 400); assert.equal((await request('/jobs/missing')).status, 404); });
  test('output replacement and unsafe IDs cannot open arbitrary paths', async () => { const { candidate } = await ready(); const { job } = await renderer.enqueue({ candidateId: candidate.id }); await renderer.waitForIdle(); fs.appendFileSync(path.join(output, `${job.id}.mp4`), 'changed'); await assert.rejects(() => renderer.openPreview(job.id), /indisponivel/); await assert.rejects(() => renderer.openPreview('../fixture'), /Identificador/); });
  test('migration maintains integrity and relational constraints', async () => { await ready(); assert.equal((await client.$queryRawUnsafe('PRAGMA integrity_check'))[0].integrity_check, 'ok'); assert.deepEqual(await client.$queryRawUnsafe('PRAGMA foreign_key_check'), []); });
  test('caption export follows the rendered transcript and shifts the real clip interval', async () => { const { candidate } = await ready(); const { job } = await renderer.enqueue({ candidateId: candidate.id }); await renderer.waitForIdle(); const result = await renderer.captions(job.id); assert.equal(result.available, true); assert.equal(result.cueCount, 3); assert.equal(result.cues[0].startMs, 0); assert.equal(result.cues.at(-1).endMs, 5000); assert.equal(result.cues[1].text, 'Consegui finalmente chegar ao outro lado!'); assert.match((await renderer.captionFile(job.id, 'vtt')).text, /^WEBVTT/); assert.equal(await client.libraryItem.count(), 2); });
  test('caption export blocks jobs invalidated after rendering', async () => { const { candidate } = await ready(); const { job } = await renderer.enqueue({ candidateId: candidate.id }); await renderer.waitForIdle(); await shorts.editCandidate(candidate.id, { title: 'Nova selecao exigida' }); await assert.rejects(() => renderer.captions(job.id), (error) => error.code === 'OUTPUT_NOT_READY'); });
  test('caption export rechecks freshness after reading source segments', async () => { const { candidate } = await ready(); const { job } = await renderer.enqueue({ candidateId: candidate.id }); await renderer.waitForIdle(); const segments = new Proxy(client.timedTranscriptSegment, { get(target, key) { if (key === 'findMany') return async (args) => { const result = await target.findMany(args); await shorts.editCandidate(candidate.id, { title: 'Editado durante exportacao' }); return result; }; const value = target[key]; return typeof value === 'function' ? value.bind(target) : value; } }); const wrapped = new Proxy(client, { get(target, key) { if (key === 'timedTranscriptSegment') return segments; const value = target[key]; return typeof value === 'function' ? value.bind(target) : value; } }); const guarded = new ClipRenderService(wrapped, files, new MediaProbe(), createRenderRunner(), output); await guarded.initialize(); await assert.rejects(() => guarded.captions(job.id), (error) => error.code === 'OUTPUT_OUTDATED'); });
});
