const assert = require('node:assert/strict');
const { before, after, beforeEach, describe, test } = require('node:test');
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path'); const { execFileSync } = require('node:child_process'); const express = require('express');
process.env.DATABASE_URL = ':memory:';
const { DatabaseService } = require('../dist/database/DatabaseService');
const { MediaFiles, MediaProbe, MediaSourceService, MediaError, createProbeRunner, parseByteRange, safeRelativePath } = require('../dist/services/media');
const { createMediaRouter } = require('../dist/routes/media');
const { ProductionService } = require('../dist/services/production');
const { ProductionRepository } = require('../dist/database/repositories/ProductionRepository');
const { ChaptersService } = require('../dist/services/chapters');
const { ChapterRepository } = require('../dist/database/repositories/ChapterRepository');
const { ShortsService } = require('../dist/services/shorts');
const { ShortsRepository } = require('../dist/database/repositories/ShortsRepository');

describe('Local media path and range policy', () => {
  test('accepts a nested local video path', () => assert.equal(safeRelativePath('finalizados/video.mp4'), 'finalizados/video.mp4'));
  test('rejects traversal absolute UNC URL encoded and ambiguous paths', () => { for (const input of ['../video.mp4', 'folder/../video.mp4', 'C:\\video.mp4', '/video.mp4', '\\\\host\\share\\video.mp4', 'http://site/video.mp4', 'video.mp4:stream', 'x%2fvideo.mp4', './video.mp4', 'folder./video.mp4', 'video.mp4?x=1', 'folder//video.mp4', 'CON.mp4', 'NUL/video.mp4', 'movie*.mp4']) assert.throws(() => safeRelativePath(input), MediaError); });
  test('rejects playlists scripts and nonvideo extensions', () => { for (const input of ['playlist.m3u8', 'movie.txt', 'script.exe', 'audio.mp3']) assert.throws(() => safeRelativePath(input), MediaError); });
  test('parses bounded open and suffix single byte ranges', () => { assert.deepEqual(parseByteRange('bytes=2-4', 10), { start: 2, end: 4, partial: true }); assert.equal(parseByteRange('bytes=5-', 10).end, 9); assert.equal(parseByteRange('bytes=-3', 10).start, 7); assert.equal(parseByteRange(undefined, 10).partial, false); });
  test('rejects multiple overflowing malformed and unavailable ranges', () => { for (const input of ['bytes=1-2,5-6', 'bytes=10-', 'bytes=5-2', 'bytes=-0', 'bytes=9007199254740993-', 'items=1-2', 'bytes=-']) assert.throws(() => parseByteRange(input, 10), MediaError); });
});

describe('Local media probing persistence and preview', { concurrency: false }, () => {
  let client; let temp; let root; let rootId; let fixture; let files; let service; let production; let server; let url;
  const mediaPath = () => path.join(root, 'sample.mp4');
  before(async () => {
    temp = fs.mkdtempSync(path.join(os.tmpdir(), 'jvitorz-media-test-')); root = path.join(temp, 'allowed'); fs.mkdirSync(root);
    fixture = path.join(temp, 'fixture.mp4');
    execFileSync('ffmpeg', ['-hide_banner', '-loglevel', 'error', '-f', 'lavfi', '-i', 'color=c=blue:s=160x90:d=1', '-f', 'lavfi', '-i', 'sine=frequency=440:duration=1', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-shortest', '-y', fixture], { windowsHide: true, timeout: 20000, stdio: 'pipe' });
    client = await DatabaseService.connect();
    for (const directory of fs.readdirSync(path.resolve(__dirname, '../prisma/migrations')).sort()) { const file = path.resolve(__dirname, '../prisma/migrations', directory, 'migration.sql'); if (!fs.existsSync(file)) continue; for (const statement of fs.readFileSync(file, 'utf8').split(';').map((part) => part.replace(/^--.*$/gm, '').trim()).filter(Boolean)) await client.$executeRawUnsafe(statement); }
    await client.$executeRawUnsafe('PRAGMA foreign_keys = ON');
    files = new MediaFiles([root]); rootId = (await files.roots())[0].id; production = new ProductionService(new ProductionRepository(client)); service = new MediaSourceService(client, files, new MediaProbe(), production);
    const app = express(); app.use(express.json()); app.use('/api/media', createMediaRouter(service)); server = await new Promise((resolve) => { const value = app.listen(0, '127.0.0.1', () => resolve(value)); }); url = `http://127.0.0.1:${server.address().port}/api/media`;
  });
  after(async () => { await new Promise((resolve) => server.close(resolve)); await DatabaseService.disconnect(); const resolved = path.resolve(temp); assert.ok(resolved.startsWith(path.resolve(os.tmpdir()) + path.sep) && path.basename(resolved).startsWith('jvitorz-media-test-')); fs.rmSync(resolved, { recursive: true, force: true }); });
  beforeEach(async () => { await client.shortAnalysis.deleteMany(); await client.chapterSet.deleteMany(); await client.timedTranscript.deleteMany(); await client.contentProduction.deleteMany(); await client.localMediaSource.deleteMany(); await client.libraryItem.deleteMany(); fs.copyFileSync(fixture, mediaPath()); });
  const register = (extra = {}) => service.register({ rootId, relativePath: 'sample.mp4', ...extra });
  const request = async (route, method = 'GET', body) => { const response = await fetch(`${url}${route}`, { method, headers: { 'content-type': 'application/json' }, ...(body !== undefined ? { body: JSON.stringify(body) } : {}) }); return { status: response.status, body: await response.json() }; };
  test('health reports real ffprobe capability', async () => assert.equal((await service.health()).available, true));
  test('roots and source responses never expose absolute paths', async () => { const roots = await service.roots(); assert.deepEqual(Object.keys(roots[0]).sort(), ['id', 'label']); const result = await register(); const serialized = JSON.stringify(result); assert.ok(!serialized.includes(root.replace(/\\/g, '\\\\'))); assert.ok(!serialized.includes('absolutePath')); assert.ok(!serialized.includes('identityKey')); });
  test('real ffprobe registers video and audio metadata in the existing Library', async () => { const { source, created } = await register({ title: 'Clip real' }); assert.equal(created, true); assert.equal(source.status, 'READY'); assert.equal(source.width, 160); assert.equal(source.height, 90); assert.equal(source.hasAudio, true); assert.equal(source.videoCodec, 'h264'); assert.equal(source.audioCodec, 'aac'); assert.ok(source.durationMs >= 1000); assert.equal(await client.libraryItem.count(), 1); assert.equal((await client.libraryItem.findUnique({ where: { id: source.libraryItemId } })).content, null); });
  test('duplicate and concurrent registration reuse one source and Library item', async () => { const results = await Promise.all([register(), register(), register()]); assert.equal(new Set(results.map(({ source }) => source.id)).size, 1); assert.equal(await client.localMediaSource.count(), 1); assert.equal(await client.libraryItem.count(), 1); });
  test('invalid directory root and path registrations fail before persistence', async () => { fs.mkdirSync(path.join(root, 'dir.mp4'), { recursive: true }); await assert.rejects(() => register({ relativePath: 'dir.mp4' }), /regular media file/); await assert.rejects(() => register({ rootId: 'missing' }), MediaError); await assert.rejects(() => register({ relativePath: '../fixture.mp4' }), MediaError); assert.equal(await client.localMediaSource.count(), 0); });
  test('symlink or junction path escapes are rejected', async () => { const outside = path.join(temp, 'outside'); fs.mkdirSync(outside, { recursive: true }); fs.copyFileSync(fixture, path.join(outside, 'video.mp4')); const link = path.join(root, 'linked'); fs.symlinkSync(outside, link, process.platform === 'win32' ? 'junction' : 'dir'); await assert.rejects(() => service.register({ rootId, relativePath: 'linked/video.mp4' }), /Symbolic links/); });
  test('playlist disguised as mp4 is rejected by closed format whitelist', async () => { fs.writeFileSync(path.join(root, 'playlist.mp4'), '#EXTM3U\nhttp://127.0.0.1:9/secret.ts\n'); const result = await register({ relativePath: 'playlist.mp4' }); assert.equal(result.source.status, 'ERROR'); assert.equal(result.source.durationMs, null); assert.equal(result.source.errorCode, 'PROBE_FAILED'); });
  test('probe runner receives only safe argument arrays and bounded policy', async () => { let observed; const probe = new MediaProbe(async (args, limits) => { observed = { args, limits }; return JSON.stringify({ format: { format_name: 'mov,mp4', duration: '1' }, streams: [{ codec_type: 'video', codec_name: 'h264', width: 160, height: 90 }] }); }); await probe.probe('local-file.mp4'); assert.ok(observed.args.includes('-protocol_whitelist')); assert.equal(observed.args[observed.args.indexOf('-protocol_whitelist') + 1], 'file'); assert.ok(!observed.args.includes('-show_format')); assert.ok(observed.limits.timeoutMs <= 15000); });
  test('missing ffprobe is explicit and stores no invented metadata', async () => { const offline = new MediaSourceService(client, files, new MediaProbe(createProbeRunner('missing-jvitorz-ffprobe-executable')), production); assert.equal((await offline.health()).available, false); const result = await offline.register({ rootId, relativePath: 'sample.mp4' }); assert.equal(result.source.status, 'UNAVAILABLE'); assert.equal(result.source.videoCodec, null); assert.equal(result.source.errorCode, 'PROBE_UNAVAILABLE'); });
  test('timeout and invalid probe output yield safe error status', async () => { const timeout = new MediaSourceService(client, files, new MediaProbe(async () => { throw new MediaError('PROBE_TIMEOUT', 'timeout'); }), production); const result = await timeout.register({ rootId, relativePath: 'sample.mp4' }); assert.equal(result.source.status, 'ERROR'); assert.equal(result.source.errorCode, 'PROBE_TIMEOUT'); const invalid = new MediaProbe(async () => 'not-json'); await assert.rejects(() => invalid.probe('file.mp4'), /invalid metadata/); });
  test('runner kills hung and excessive-output subprocesses', async () => { const runner = createProbeRunner(process.execPath); await assert.rejects(() => runner(['-e', 'setTimeout(() => {}, 5000)'], { timeoutMs: 30, maxOutputBytes: 1000 }), (error) => error.code === 'PROBE_TIMEOUT'); await assert.rejects(() => runner(['-e', 'process.stdout.write("x".repeat(10000))'], { timeoutMs: 3000, maxOutputBytes: 100 }), (error) => error.code === 'PROBE_OUTPUT_LIMIT'); });
  test('malformed stream entries are a typed metadata error', async () => { const probe = new MediaProbe(async () => JSON.stringify({ format: { duration: '1' }, streams: [null] })); await assert.rejects(() => probe.probe('file.mp4'), (error) => error instanceof MediaError && error.code === 'PROBE_INVALID_OUTPUT'); });
  test('file mutation during probing cannot be registered as stable', async () => { const runner = createProbeRunner(); const mutating = new MediaSourceService(client, files, new MediaProbe(async (args, options) => { const output = await runner(args, options); fs.appendFileSync(mediaPath(), 'changed'); return output; }), production); await assert.rejects(() => mutating.register({ rootId, relativePath: 'sample.mp4' }), /changed during probing/); assert.equal(await client.localMediaSource.count(), 0); });
  test('changed files block preview until explicit reprobe', async () => { const { source } = await register(); fs.appendFileSync(mediaPath(), 'changed'); assert.equal((await service.get(source.id)).status, 'CHANGED'); await assert.rejects(() => service.openPreview(source.id), /successfully probed/); const result = await service.reprobe(source.id); assert.equal(result.changed, true); assert.equal(result.source.status, 'READY'); assert.notEqual(result.source.fingerprint, source.fingerprint); });
  test('offline source is explicit and recovery requires reprobe', async () => { const { source } = await register(); fs.unlinkSync(mediaPath()); assert.equal((await service.get(source.id)).status, 'OFFLINE'); fs.copyFileSync(fixture, mediaPath()); assert.equal((await service.get(source.id)).status, 'CHANGED'); assert.equal((await service.reprobe(source.id)).source.status, 'READY'); });
  test('unchanged reprobe is idempotent in identity and fingerprint', async () => { const { source } = await register(); const result = await service.reprobe(source.id); assert.equal(result.changed, false); assert.equal(result.source.id, source.id); assert.equal(result.source.fingerprint, source.fingerprint); assert.equal(await client.localMediaSource.count(), 1); });
  test('stale check cannot overwrite a concurrently accepted reprobe', async () => { const { source } = await register(); fs.appendFileSync(mediaPath(), 'changed'); let release; let seen; const wait = new Promise((resolve) => { release = resolve; }); const entered = new Promise((resolve) => { seen = resolve; }); let first = true; const controlledFiles = new MediaFiles([root]); const actualResolve = controlledFiles.resolve.bind(controlledFiles); controlledFiles.resolve = async (...args) => { const resolved = await actualResolve(...args); if (first) { first = false; seen(); await wait; } return resolved; }; const concurrent = new MediaSourceService(client, controlledFiles, new MediaProbe(), production); const pending = concurrent.get(source.id); await entered; const probed = await service.reprobe(source.id); assert.equal(probed.source.status, 'READY'); release(); const checked = await pending; assert.equal(checked.status, 'READY'); assert.equal(checked.fingerprint, probed.source.fingerprint); assert.equal((await service.get(source.id)).status, 'READY'); });
  test('registration links the existing Library item to Production', async () => { const { production: row } = await production.create({ title: 'Media production', productionKey: 'media' }); const result = await register({ productionId: row.id, role: 'EDITED_VIDEO' }); assert.deepEqual(result.source.productions, [{ productionId: row.id, role: 'EDITED_VIDEO' }]); const refreshed = await production.get(row.id); assert.equal(refreshed.assets[0].libraryItemId, result.source.libraryItemId); });
  test('file changes invalidate associated Shorts analysis and output', async () => { const { production: row } = await production.create({ title: 'Media clipping', productionKey: 'clips' }); const { source } = await register({ productionId: row.id, role: 'EDITED_VIDEO' }); for (const key of ['PREPARING', 'EDITING']) { await production.startStep(row.id, key); await production.completeStep(row.id, key); } const chapters = new ChaptersService(new ChapterRepository(client), production); await chapters.importTranscript({ productionId: row.id, format: 'INTERNAL', segments: [{ startMs: 0, endMs: 10000, text: 'Consegui finalmente!' }] }); await production.skipStep(row.id, 'CHAPTERS', { reason: 'Teste' }); const shorts = new ShortsService(new ShortsRepository(client), production, { resolve: async () => ({ entries: [] }) }); const { analysis } = await shorts.analyze(row.id); fs.appendFileSync(mediaPath(), 'new'); await service.get(source.id); assert.equal((await client.shortAnalysis.findUnique({ where: { id: analysis.id } })).status, 'STALE'); assert.equal((await production.get(row.id)).steps.find(({ key }) => key === 'SHORTS').state, 'OUTDATED'); });
  test('preview streams exact requested bytes from authorized file handle', async () => { const { source } = await register(); const response = await fetch(`${url}/sources/${source.id}/preview`, { headers: { Range: 'bytes=2-15' } }); assert.equal(response.status, 206); assert.equal(response.headers.get('content-length'), '14'); assert.equal(response.headers.get('content-type'), 'video/mp4'); assert.deepEqual(Buffer.from(await response.arrayBuffer()), fs.readFileSync(mediaPath()).subarray(2, 16)); });
  test('preview HEAD and suffix ranges work and malformed ranges return 416', async () => { const { source } = await register(); const head = await fetch(`${url}/sources/${source.id}/preview`, { method: 'HEAD' }); assert.equal(head.status, 200); assert.equal((await head.arrayBuffer()).byteLength, 0); const suffix = await fetch(`${url}/sources/${source.id}/preview`, { headers: { Range: 'bytes=-10' } }); assert.equal((await suffix.arrayBuffer()).byteLength, 10); const invalid = await fetch(`${url}/sources/${source.id}/preview`, { headers: { Range: 'bytes=1-2,4-5' } }); assert.equal(invalid.status, 416); assert.match(invalid.headers.get('content-range'), /^bytes \*\//); });
  test('HTTP registry health roots list get reprobe and sanitized errors', async () => { assert.equal((await request('/health')).status, 200); assert.equal((await request('/roots')).body[0].id, rootId); const created = await request('/sources', 'POST', { rootId, relativePath: 'sample.mp4' }); assert.equal(created.status, 201); assert.equal((await request(`/sources/${created.body.source.id}`)).status, 200); assert.equal((await request('/sources')).body.length, 1); assert.equal((await request(`/sources/${created.body.source.id}/reprobe`, 'POST', {})).status, 200); const error = await request('/sources', 'POST', { rootId, relativePath: '../secret.mp4' }); assert.equal(error.status, 400); assert.doesNotMatch(JSON.stringify(error.body), /absolutePath|Prisma|stack|secret/); });
  test('migration maintains SQLite integrity and foreign keys', async () => { await register(); assert.equal((await client.$queryRawUnsafe('PRAGMA integrity_check'))[0].integrity_check, 'ok'); assert.deepEqual(await client.$queryRawUnsafe('PRAGMA foreign_key_check'), []); });
});
