const assert = require('node:assert/strict');
const { after, before, beforeEach, describe, test } = require('node:test');
const fs = require('node:fs'); const path = require('node:path'); const express = require('express');
process.env.DATABASE_URL = ':memory:';
const { DatabaseService } = require('../dist/database/DatabaseService');
const { PackagingRepository } = require('../dist/database/repositories/PackagingRepository');
const { PackagingService } = require('../dist/services/packaging');
const { generatePackagingVariants, reviewPackagingVariant } = require('../dist/domains/packaging');
const { createPackagingRouter } = require('../dist/routes/packaging');
const { classifyManagerIntent } = require('../dist/services/orchestration/ManagerIntentInterpreter');
const { createDefaultCapabilityRegistry } = require('../dist/services/orchestration/OrchestrationComposition');
const { SupervisorModule } = require('../dist/modules/dashboard/supervisor/SupervisorModule');

const runSql = async (client, file) => { const sql = fs.readFileSync(file, 'utf8'); for (const statement of sql.split(';').map((part) => part.replace(/^--.*$/gm, '').trim()).filter(Boolean)) await client.$executeRawUnsafe(statement); };
const context = [{ id: 'ctx-city', type: 'DECISION', subject: 'Identidade City', statement: 'Preto e laranja.', confidence: 1 }];
const input = (overrides = {}) => ({ game: 'City Car Driving 2.0', series: 'Vida de Motorista', episode: 9, format: 'LONG_FORM', summary: 'Uma entrega terminou com pane no carro.', keyEvents: ['o carro quebrou durante a entrega'], variationCount: 3, ...overrides });

describe('packaging intelligence', { concurrency: false }, () => {
  let client; let repository; let service; let server; let baseUrl; let memory;
  before(async () => {
    client = await DatabaseService.connect(); await client.$executeRawUnsafe('PRAGMA foreign_keys = ON');
    await client.$executeRawUnsafe('CREATE TABLE "Project" ("id" TEXT NOT NULL PRIMARY KEY)');
    await client.$executeRawUnsafe('CREATE TABLE "VideoPerformanceSnapshot" ("id" TEXT NOT NULL PRIMARY KEY)');
    await runSql(client, path.resolve(__dirname, '../prisma/migrations/20260912120000_packaging_intelligence/migration.sql'));
    repository = new PackagingRepository(client); memory = [];
    const memoryService = { create: async (entry) => { const created = { id: `ctx-${memory.length + 1}`, ...entry }; memory.push(created); return created; }, relate: async (...args) => memory.push({ relation: args }) };
    service = new PackagingService(repository, { resolve: async () => ({ entries: context, truncated: false }) }, memoryService,
      { findAll: async () => [] }, { findAll: async () => [] }, () => new Date('2026-09-12T12:00:00Z'));
    const app = express(); app.use(express.json()); app.use('/api/packaging', createPackagingRouter(service)); server = await new Promise((resolve) => { const current = app.listen(0, '127.0.0.1', () => resolve(current)); }); baseUrl = `http://127.0.0.1:${server.address().port}/api/packaging`;
  });
  after(async () => { await new Promise((resolve) => server.close(resolve)); await DatabaseService.disconnect(); });
  beforeEach(async () => { await client.packagingMetricSnapshot.deleteMany(); await client.packagingExperiment.deleteMany(); await client.packagingHistory.deleteMany(); await client.packagingVariant.deleteMany(); await client.contentPackaging.deleteMany(); memory.length = 0; });
  const request = async (url = '', options = {}) => { const response = await fetch(`${baseUrl}${url}`, { headers: { 'content-type': 'application/json' }, ...options }); return { status: response.status, body: await response.json() }; };

  test('generator creates contextual deterministic variants without mutation', () => { const value = input(); const copy = structuredClone(value); const variants = generatePackagingVariants(value, context); assert.equal(variants.length, 3); assert.deepEqual(value, copy); assert.ok(variants.every(({ title }) => /quebrou/i.test(title))); assert.deepEqual(variants[0].contextUsed, ['ctx-city']); });
  test('City Car and Forza preserve distinct current identities', () => { const city = generatePackagingVariants(input(), context)[0]; const forza = generatePackagingVariants(input({ game: 'Forza Horizon 6', series: null, episode: null, keyEvents: ['encontrei um carro raro abandonado'] }), context)[0]; assert.ok(city.thumbnailBrief.requiredElements.includes('preto e laranja')); assert.ok(forza.thumbnailBrief.requiredElements.includes('carro como protagonista')); assert.match(forza.thumbnailBrief.text, /RARO/); });
  test('title thumbnail description and tags remain faithful and complementary', () => { const variant = generatePackagingVariants(input(), context)[0]; assert.match(variant.title, /carro quebrou/i); assert.notEqual(variant.thumbnailBrief.text.toLowerCase(), variant.title.toLowerCase()); assert.match(variant.description, /pane/); assert.ok(variant.tags.includes('City Car Driving 2.0')); });
  test('review detects unsupported event and misleading clickbait', () => { const review = reviewPackagingVariant({ title: 'Voce nao vai acreditar no melhor do mundo', sourceEvent: 'o carro quebrou', thumbnailBrief: { text: 'x' }, contextUsed: ['ctx'] }); assert.equal(review.valid, false); assert.ok(review.findings.some(({ code }) => code === 'MISLEADING_CLICKBAIT')); });
  test('service persists variants and append-only generation history', async () => { const result = await service.generate(input()); assert.equal(result.variants.length, 3); assert.equal(result.history[0].event, 'GENERATED'); assert.equal((await service.list()).length, 1); assert.equal((await service.get(result.id)).contextSnapshot[0].id, 'ctx-city'); });
  test('selection and rejection preserve variants history and memory', async () => { const created = await service.generate(input()); const selected = await service.selectVariant(created.variants[0].id, 'Melhor encaixe'); const rejected = await service.rejectVariant(created.variants[1].id, 'Muito longo'); assert.equal(selected.variants.find(({ id }) => id === created.variants[0].id).status, 'SELECTED'); assert.equal(rejected.variants.find(({ id }) => id === created.variants[1].id).status, 'REJECTED'); assert.ok(rejected.history.some(({ event }) => event === 'SELECTED')); assert.ok(memory.some(({ type }) => type === 'DECISION')); });
  test('manual edits are creator decisions and remain auditable', async () => { const created = await service.generate(input()); const updated = await service.editVariant(created.variants[0].id, { title: 'Ep. 9: O carro quebrou na entrega', reason: 'Voz natural' }); const variant = updated.variants[0]; assert.equal(variant.manualEdits.title, 'Ep. 9: O carro quebrou na entrega'); assert.ok(updated.history.some(({ event }) => event === 'EDITED')); assert.ok(memory.some(({ statement }) => /nao um erro/.test(statement))); });
  test('publication is explicit and does not modify YouTube', async () => { const created = await service.generate(input()); const result = await service.publishVariant(created.variants[0].id, { videoId: 'youtube-video' }); assert.equal(result.variants[0].publishedVideoId, 'youtube-video'); assert.equal(result.variants[0].status, 'PUBLISHED'); assert.ok(result.history.some(({ event }) => event === 'PUBLISHED')); });
  test('missing Analytics and CTR metrics are explicit', async () => { const created = await service.generate(input()); await service.publishVariant(created.variants[0].id, { videoId: 'missing-video' }); const observed = await service.observeVariant(created.variants[0].id); assert.equal(observed.snapshot, null); assert.deepEqual(observed.missingData, ['performance', 'reach']); });
  test('real Analytics and CTR snapshots are copied without causal claims', async () => {
    await client.$executeRawUnsafe(`INSERT OR IGNORE INTO "VideoPerformanceSnapshot" ("id") VALUES ('performance')`);
    const local = new PackagingService(repository, { resolve: async () => ({ entries: context }) }, { create: async (entry) => ({ id: 'memory-fact', ...entry }), relate: async () => {} },
      { findAll: async () => [{ id: 'performance', source: 'youtube-analytics', views: 100, watchTimeMinutes: 20, averageViewDurationSeconds: 30, averageViewPercentage: 45, impressions: null, ctr: null, subscribersGained: 2, likes: 8, periodStart: new Date('2026-09-01'), periodEnd: new Date('2026-09-02'), confidence: 1 }] },
      { findAll: async () => [{ id: 'reach', source: 'youtube-reporting', impressions: 1000, ctr: 5.4, periodStart: new Date('2026-09-01'), periodEnd: new Date('2026-09-02'), qualityAtCollection: 'GOOD' }] });
    const created = await local.generate(input()); await local.publishVariant(created.variants[0].id, { videoId: 'real-video' }); const observed = await local.observeVariant(created.variants[0].id); assert.equal(observed.snapshot.metrics.ctr, 5.4); assert.equal(observed.snapshot.metrics.views, 100); assert.equal((await local.get(created.id)).variants[0].metricSnapshots.length, 1);
  });
  test('packaging experiment is typed in Creator Memory', async () => { const created = await service.generate(input()); const experiment = await service.createExperiment(created.id, { hypothesis: 'Texto curto pode se associar a CTR diferente.', variantIds: created.variants.slice(0, 2).map(({ id }) => id) }); assert.equal(experiment.status, 'ACTIVE'); assert.ok(memory.some(({ type }) => type === 'EXPERIMENT')); });
  test('learning requires multiple real observations and remains non-causal', async () => { const created = await service.generate(input()); await assert.rejects(() => service.recordLearning(created.id), /two observed/); for (const [index, variant] of created.variants.slice(0, 2).entries()) await repository.saveMetric({ variantId: variant.id, ingestionKey: `learning-${index}`, videoId: `video-${index}`, metrics: { ctr: 4 + index }, source: 'test', confidence: 1 }); const learning = await service.recordLearning(created.id); assert.equal(learning.type, 'LEARNING'); assert.match(learning.statement, /nao demonstra causalidade/); });
  test('HTTP generation list detail and history expose persisted records', async () => { const created = await request('', { method: 'POST', body: JSON.stringify(input()) }); assert.equal(created.status, 201); assert.equal((await request('')).body.length, 1); assert.equal((await request(`/${created.body.id}`)).body.variants.length, 3); assert.equal((await request(`/${created.body.id}/history`)).body[0].event, 'GENERATED'); });
  test('HTTP variant actions and strict errors use safe statuses', async () => { const created = (await request('', { method: 'POST', body: JSON.stringify(input()) })).body; const [a, b] = created.variants; assert.equal((await request(`/variants/${a.id}`, { method: 'PATCH', body: '{"title":"Ep. 9: o carro quebrou"}' })).status, 200); assert.equal((await request(`/variants/${a.id}/select`, { method: 'POST', body: '{}' })).status, 200); assert.equal((await request(`/variants/${b.id}/reject`, { method: 'POST', body: '{}' })).status, 200); assert.equal((await request(`/variants/${a.id}/review`)).status, 200); assert.equal((await request(`/variants/${a.id}/publish`, { method: 'POST', body: '{"videoId":"v1"}' })).status, 200); assert.equal((await request(`/variants/${a.id}/observe`, { method: 'POST', body: '{}' })).status, 200); assert.equal((await request('', { method: 'POST', body: '{"summary":"x","keyEvents":[],"secret":"x"}' })).status, 400); assert.equal((await request('/missing')).status, 404); });
  test('Manager recognizes packaging and reads consolidated variants', async () => { assert.equal(classifyManagerIntent('Me ajuda com o titulo e a thumb desse video'), 'PACKAGING'); const registry = createDefaultCapabilityRegistry({ packaging: { list: async () => [{ id: 'p', game: 'Forza', variants: [{ id: 'a', key: 'A', title: 'Carro raro encontrado', status: 'DRAFT', rationale: 'Evento real.' }] }] } }); const output = await registry.get('packaging.read').execute({ request: { intent: 'titulo' }, results: new Map() }); assert.match(output.facts[0], /Carro raro/); });
  test('Supervisor exposes packaging status without replacing creator choice', async () => { const args = Array(17).fill(undefined); args.push({ getOperationalSummary: async () => ({ total: 2, selected: 1, published: 0, experiments: 1, needingReview: 0 }) }); const overview = await new SupervisorModule(...args).getSupervisorOverview(); assert.equal(overview.packaging.selected, 1); assert.ok(overview.dataQuality.some(({ area }) => area === 'Packaging')); });
});
