const assert = require('node:assert/strict');
const { before, after, beforeEach, describe, test } = require('node:test');
const fs = require('node:fs'); const path = require('node:path'); const express = require('express');
process.env.DATABASE_URL = ':memory:';
const { DatabaseService } = require('../dist/database/DatabaseService');
const { ProductionRepository } = require('../dist/database/repositories/ProductionRepository');
const { ChapterRepository } = require('../dist/database/repositories/ChapterRepository');
const { ShortsRepository } = require('../dist/database/repositories/ShortsRepository');
const { ProductionService } = require('../dist/services/production');
const { ChaptersService } = require('../dist/services/chapters');
const { ShortsService, ShortsConflictError, ShortsValidationError } = require('../dist/services/shorts');
const { detectClips, clipConfiguration, describeClip, reviewClips } = require('../dist/domains/shorts');
const { SupervisorModule } = require('../dist/modules/dashboard/supervisor/SupervisorModule');
const { createShortsRouter } = require('../dist/routes/shorts');
const { createDefaultCapabilityRegistry } = require('../dist/services/orchestration/OrchestrationComposition');
const { classifyManagerIntent } = require('../dist/services/orchestration/ManagerIntentInterpreter');
const segments = () => [
  { startMs: 0, endMs: 6000, text: 'Vou tentar passar pela ponte agora.' },
  { startMs: 6000, endMs: 12000, text: 'Nossa, quase cai da ponte!' },
  { startMs: 12000, endMs: 18000, text: 'Consegui chegar ao outro lado, finalmente!' },
  { startMs: 18000, endMs: 24000, text: 'Agora seguimos pela estrada.' },
  { startMs: 60000, endMs: 66000, text: 'Estou procurando uma passagem.' },
  { startMs: 66000, endMs: 72000, text: 'Descobri um caminho novo aqui.' },
  { startMs: 72000, endMs: 78000, text: 'Pronto, resolvi o problema.' },
];
const domainSegments = () => segments().map((item, position) => ({ ...item, id: `s${position}`, position }));

describe('Shorts editorial domain', () => {
  test('detects events with real setup and payoff boundaries', () => { const clips = detectClips(domainSegments(), clipConfiguration()); assert.equal(clips.length, 2); assert.equal(clips[0].startMs, 0); assert.equal(clips[0].endMs, 18000); });
  test('hook is a real phrase and evidence uses references only', () => { const clip = detectClips(domainSegments(), clipConfiguration())[0]; assert.equal(clip.hook, segments()[1].text); assert.deepEqual(clip.evidence[0], { segmentId: 's0', position: 0 }); assert.ok(!('text' in clip.evidence[0])); });
  test('ranking is explainable and relative without prediction', () => { for (const clip of detectClips(domainSegments(), clipConfiguration())) { assert.equal(clip.score, clip.scoreFactors.reduce((sum, item) => sum + item.points, 0)); assert.ok(clip.scoreFactors.every(({ reason }) => reason)); assert.ok(!('predictedViews' in clip)); } });
  test('dedupe keeps one proposal per overlapping event', () => { const clips = detectClips(domainSegments(), clipConfiguration()); assert.equal(clips.filter(({ startMs }) => startMs < 24000).length, 1); });
  test('duration configuration is editorial and strict', () => { assert.throws(() => clipConfiguration({ maxDurationMs: '90000' }), ShortsValidationError); assert.throws(() => clipConfiguration({ minDurationMs: 100000, maxDurationMs: 90000 }), ShortsValidationError); assert.equal(detectClips(domainSegments(), clipConfiguration({ minDurationMs: 50000 })).length, 0); });
  test('no events means no invented candidates', () => assert.deepEqual(detectClips([{ id: 'x', position: 0, startMs: 0, endMs: 10000, text: 'Uma frase sobre o caminho.' }], clipConfiguration()), []));
  test('chapters constrain setup and evidence links to chapter', () => { const clips = detectClips(domainSegments(), clipConfiguration(), [{ id: 'c', startMs: 6000, endMs: 60000, title: 'Ponte' }]); const clip = clips.find(({ chapterEntryId }) => chapterEntryId === 'c'); assert.ok(clip.startMs >= 6000); });
  test('Supervisor rejects unsupported clickbait', () => { const data = domainSegments(); const clip = { ...describeClip(data, 0, 18000), id: 'c', hook: 'Milhoes de premios garantidos' }; assert.equal(reviewClips([clip], data, clipConfiguration()).outcome, 'NEEDS_CHANGES'); });
  test('Supervisor rejects fabricated segment evidence', () => { const data = domainSegments(); const clip = { ...describeClip(data, 0, 18000), id: 'c', evidence: [{ segmentId: 'fake' }] }; assert.equal(reviewClips([clip], data, clipConfiguration()).outcome, 'NEEDS_CHANGES'); });
  test('natural clipping requests use Production while analytics stays analytical', () => { for (const phrase of ['acha os melhores Shorts desse video', 'tem algum corte bom aqui?', 'me mostra os melhores momentos', 'seleciona candidatos dessa producao']) assert.equal(classifyManagerIntent(phrase), 'PRODUCTION'); assert.notEqual(classifyManagerIntent('mostra metricas dos shorts'), 'PRODUCTION'); });
  test('generic research candidates and idea shortlists never route to clip Production', () => { for (const phrase of ['gera candidatos de jogos', 'analisa candidato de pesquisa', 'shortlist de ideias']) assert.notEqual(classifyManagerIntent(phrase), 'PRODUCTION'); assert.equal(classifyManagerIntent('me mostra ideias de jogos candidatos para pesquisar'), 'RESEARCH_DISCOVERY'); assert.equal(classifyManagerIntent('gera titulos para Shorts'), 'PACKAGING'); assert.equal(classifyManagerIntent('me mostra ideias para Shorts'), 'RESEARCH_DISCOVERY'); });
});

describe('Shorts persistent pipeline and HTTP', { concurrency: false }, () => {
  let client; let production; let chapters; let shorts; let server; let url; let contextReads = [];
  const makeService = () => new ShortsService(new ShortsRepository(client), production, { resolve: async (query) => { contextReads.push(query); return { entries: [{ id: 'memory1', type: 'DECISION', subject: 'Estilo', statement: 'Preservar o contexto do momento.' }], truncated: false }; } }, new SupervisorModule());
  before(async () => {
    client = await DatabaseService.connect();
    for (const directory of fs.readdirSync(path.resolve(__dirname, '../prisma/migrations')).sort()) {
      const file = path.resolve(__dirname, '../prisma/migrations', directory, 'migration.sql'); if (!fs.existsSync(file)) continue;
      for (const statement of fs.readFileSync(file, 'utf8').split(';').map((part) => part.replace(/^--.*$/gm, '').trim()).filter(Boolean)) await client.$executeRawUnsafe(statement);
    }
    await client.$executeRawUnsafe('PRAGMA foreign_keys = ON');
    production = new ProductionService(new ProductionRepository(client)); chapters = new ChaptersService(new ChapterRepository(client), production); shorts = makeService();
    const app = express(); app.use(express.json()); app.use('/api/shorts', createShortsRouter(shorts));
    server = await new Promise((resolve) => { const value = app.listen(0, '127.0.0.1', () => resolve(value)); }); url = `http://127.0.0.1:${server.address().port}/api/shorts`;
  });
  after(async () => { await new Promise((resolve) => server.close(resolve)); await DatabaseService.disconnect(); });
  beforeEach(async () => { await client.shortAnalysis.deleteMany(); await client.chapterSet.deleteMany(); await client.timedTranscript.deleteMany(); await client.contentProduction.deleteMany(); await client.libraryItem.deleteMany(); contextReads = []; });
  const ready = async (key = 'clips', importData = true) => {
    const { production: row } = await production.create({ productionKey: key, title: `Video ${key}`, game: 'Jogo real', series: 'Serie real', format: 'LONG_FORM' });
    for (const step of ['PREPARING', 'EDITING']) { await production.startStep(row.id, step); await production.completeStep(row.id, step); }
    if (importData) await chapters.importTranscript({ productionId: row.id, format: 'INTERNAL', segments: segments() });
    await production.skipStep(row.id, 'CHAPTERS', { reason: 'Teste sem capitulos' }); return production.get(row.id);
  };
  const generated = async () => { const row = await ready(); return { row, analysis: (await shorts.analyze(row.id)).analysis }; };
  const request = async (route, method = 'GET', body) => { const response = await fetch(`${url}${route}`, { method, headers: { 'content-type': 'application/json' }, ...(body !== undefined ? { body: JSON.stringify(body) } : {}) }); return { status: response.status, body: await response.json() }; };
  test('analysis persists source context game series and audit without new learning', async () => { const { analysis } = await generated(); assert.equal(analysis.version, 1); assert.equal(analysis.candidates.length, 2); assert.equal(analysis.candidates[0].game, 'Jogo real'); assert.equal(analysis.context.entries[0].id, 'memory1'); assert.equal(contextReads.length, 1); assert.equal(await client.clipRevision.count(), 1); });
  test('missing transcript is explicit and leaves no analysis', async () => { const row = await ready('missing', false); await assert.rejects(() => shorts.analyze(row.id), /Timed transcript is required/); assert.equal(await client.shortAnalysis.count(), 0); });
  test('empty event analysis is valid and explainably empty', async () => { const row = await ready('quiet', false); await chapters.importTranscript({ productionId: row.id, format: 'INTERNAL', segments: [{ startMs: 0, endMs: 10000, text: 'A estrada segue por aqui.' }] }); const result = await shorts.analyze(row.id); assert.equal(result.analysis.candidates.length, 0); assert.ok(result.analysis.limitations.some((item) => item.includes('Nenhum acontecimento'))); });
  test('ordinary analyze and Production resume reuse reviewed work', async () => { const { row, analysis } = await generated(); await production.resume(row.id); const result = await shorts.analyze(row.id); assert.equal(result.created, false); assert.equal(result.analysis.id, analysis.id); assert.equal(await client.shortAnalysis.count(), 1); });
  test('concurrent service instances create one current analysis', async () => { const row = await ready(); const results = await Promise.all([shorts.analyze(row.id), makeService().analyze(row.id), makeService().analyze(row.id)]); assert.equal(new Set(results.map(({ analysis }) => analysis.id)).size, 1); assert.equal(await client.shortAnalysis.count(), 1); });
  test('shortlist select reject archive are persistent and idempotent', async () => { const { analysis } = await generated(); const clip = analysis.candidates[0]; assert.equal((await shorts.setStatus(clip.id, 'SHORTLISTED')).status, 'SHORTLISTED'); await shorts.setStatus(clip.id, 'SELECTED'); const count = await client.clipRevision.count(); await shorts.setStatus(clip.id, 'SELECTED'); assert.equal(await client.clipRevision.count(), count); await shorts.setStatus(clip.id, 'REJECTED'); assert.equal((await shorts.setStatus(clip.id, 'ARCHIVED')).status, 'ARCHIVED'); });
  test('manual boundaries preserve real timing and reject mid-sentence ranges', async () => { const { analysis } = await generated(); const clip = analysis.candidates[0]; await assert.rejects(() => shorts.editCandidate(clip.id, { startMs: 100 }), ShortsValidationError); const edited = await shorts.editCandidate(clip.id, { startMs: 6000, endMs: 18000 }); assert.equal(edited.durationMs, 12000); assert.equal(edited.manuallyEdited, true); assert.ok(edited.evidence.every(({ position }) => position >= 1)); });
  test('manual text changes persist and unsupported hook cannot be selected', async () => { const { analysis } = await generated(); const clip = await shorts.editCandidate(analysis.candidates[0].id, { title: 'Novo titulo interno', hook: 'Milhoes de premios garantidos' }); assert.equal(clip.title, 'Novo titulo interno'); assert.equal(clip.scoreFactors.find(({ factor }) => factor === 'hook').points, 0); assert.match(clip.rationale, /Hook manual/); await assert.rejects(() => shorts.setStatus(clip.id, 'SELECTED'), /Supervisor requires changes/); });
  test('explicit null timestamps are rejected rather than silently omitted', async () => { const { analysis } = await generated(); await assert.rejects(() => shorts.editCandidate(analysis.candidates[0].id, { startMs: null }), ShortsValidationError); });
  test('sibling variants remain editable and review as one explicit family', async () => { const { analysis } = await generated(); const original = analysis.candidates[0]; const first = await shorts.createManual(analysis.id, { startMs: 6000, endMs: 18000, title: 'Rapido', hook: segments()[1].text, variantOfId: original.id, variantReason: 'Menos setup' }); await shorts.createManual(analysis.id, { startMs: 0, endMs: 24000, title: 'Mais contexto', hook: segments()[1].text, variantOfId: original.id, variantReason: 'Mais reacao' }); await shorts.editCandidate(first.id, { title: 'Rapido revisado' }); assert.notEqual((await shorts.review(analysis.id)).review.outcome, 'NEEDS_CHANGES'); });
  test('reopening EDITING immediately stales analysis and prevents handoff', async () => { const { row, analysis } = await generated(); await shorts.setStatus(analysis.candidates[0].id, 'SELECTED'); await shorts.complete(analysis.id); await production.repeatStep(row.id, 'EDITING', { reason: 'Nova edicao temporal' }); assert.equal((await client.shortAnalysis.findUnique({ where: { id: analysis.id } })).status, 'STALE'); await assert.rejects(() => shorts.renderContract(row.id), ShortsConflictError); await assert.rejects(() => shorts.analyze(row.id), ShortsConflictError); });
  test('manual candidate requires evidence and refuses duplicate moments', async () => { const { analysis } = await generated(); await assert.rejects(() => shorts.createManual(analysis.id, { startMs: 0, endMs: 18000, title: 'Duplicado', hook: segments()[1].text }), ShortsConflictError); const manual = await shorts.createManual(analysis.id, { startMs: 18000, endMs: 24000, title: 'Estrada', hook: segments()[3].text }); assert.equal(manual.manuallyEdited, true); assert.equal(manual.evidence.length, 1); });
  test('explicit variants share a moment and only one can be selected', async () => { const { analysis } = await generated(); const original = analysis.candidates[0]; const variant = await shorts.createManual(analysis.id, { startMs: 6000, endMs: 18000, title: 'Direto no evento', hook: segments()[1].text, variantOfId: original.id, variantReason: 'Menos setup' }); assert.equal(variant.momentKey, original.momentKey); await shorts.setStatus(original.id, 'SELECTED'); await assert.rejects(() => shorts.setStatus(variant.id, 'SELECTED'), /one variant/); });
  test('evidence loads exactly the temporal source range', async () => { const { analysis } = await generated(); const result = await shorts.evidence(analysis.candidates[0].id); assert.equal(result.transcriptId, analysis.transcriptId); assert.deepEqual(result.segments.map(({ text }) => text), segments().slice(0, 3).map(({ text }) => text)); });
  test('Supervisor review is persisted', async () => { const { analysis } = await generated(); const reviewed = await shorts.review(analysis.id); assert.match(reviewed.review.outcome, /APPROVED/); assert.equal((await shorts.getAnalysis(analysis.id)).review.outcome, reviewed.review.outcome); });
  test('selected clips complete Production and repeated completion does not duplicate events', async () => { const { row, analysis } = await generated(); await shorts.setStatus(analysis.candidates[0].id, 'SELECTED'); const result = await shorts.complete(analysis.id); assert.equal(result.production.steps.find(({ key }) => key === 'SHORTS').state, 'COMPLETED'); assert.equal(result.production.nextAction.stepKey, 'PACKAGING'); await shorts.complete(analysis.id); assert.equal(await client.productionEvent.count({ where: { productionId: row.id, event: 'SHORTS_COMPLETED' } }), 1); });
  test('manual Production completion cannot bypass candidate review', async () => { const row = await ready(); await production.startStep(row.id, 'SHORTS'); await assert.rejects(() => production.completeStep(row.id, 'SHORTS'), /selected clip candidates/); });
  test('empty selection cannot complete and optional skip remains available', async () => { const { row, analysis } = await generated(); await assert.rejects(() => shorts.complete(analysis.id), /Select at least one/); assert.equal((await production.skipStep(row.id, 'SHORTS', { reason: 'Sem cortes' })).steps.find(({ key }) => key === 'SHORTS').state, 'SKIPPED'); });
  test('regeneration preserves manual revisions and supersedes only explicitly', async () => { const { row, analysis } = await generated(); await shorts.editCandidate(analysis.candidates[0].id, { title: 'Manual protegido' }); const next = await shorts.analyze(row.id, {}, true); assert.equal(next.analysis.version, 2); const old = await shorts.getAnalysis(analysis.id); assert.equal(old.status, 'SUPERSEDED'); assert.equal(old.candidates[0].title, 'Manual protegido'); await assert.rejects(() => shorts.setStatus(old.candidates[0].id, 'SELECTED'), ShortsConflictError); });
  test('changed transcript invalidates candidates and production transactionally', async () => { const { row, analysis } = await generated(); await shorts.setStatus(analysis.candidates[0].id, 'SELECTED'); await shorts.complete(analysis.id); await chapters.importTranscript({ productionId: row.id, format: 'INTERNAL', segments: [...segments(), { startMs: 90000, endMs: 96000, text: 'Fim real.' }] }); assert.equal((await client.shortAnalysis.findUnique({ where: { id: analysis.id } })).status, 'STALE'); assert.equal((await production.get(row.id)).steps.find(({ key }) => key === 'SHORTS').state, 'OUTDATED'); assert.equal((await shorts.selected(row.id)).length, 0); await assert.rejects(() => shorts.setStatus(analysis.candidates[0].id, 'SELECTED'), ShortsConflictError); });
  test('editing a selected clip clears selection and completed output', async () => { const { row, analysis } = await generated(); await shorts.setStatus(analysis.candidates[0].id, 'SELECTED'); await shorts.complete(analysis.id); const edited = await shorts.editCandidate(analysis.candidates[0].id, { title: 'Revisado' }); assert.equal(edited.status, 'SHORTLISTED'); const step = (await production.get(row.id)).steps.find(({ key }) => key === 'SHORTS'); assert.equal(step.state, 'WAITING_USER'); assert.equal(step.output, null); });
  test('Library handoff references existing asset without copying media', async () => { const row = await ready(); const asset = await client.libraryItem.create({ data: { title: 'Video editado', type: 'video', content: 'local reference' } }); await production.linkAsset(row.id, asset.id, 'EDITED_VIDEO'); const analysis = (await shorts.analyze(row.id)).analysis; await shorts.setStatus(analysis.candidates[0].id, 'SELECTED'); await shorts.complete(analysis.id); const result = await shorts.renderContract(row.id); assert.equal(result.renderReady, true); assert.equal(result.clips[0].sourceAssetId, asset.id); assert.equal(result.clips[0].captions.transcriptId, analysis.transcriptId); assert.equal(await client.libraryItem.count(), 1); });
  test('handoff states missing source video honestly', async () => { const { row, analysis } = await generated(); await shorts.setStatus(analysis.candidates[0].id, 'SELECTED'); await shorts.complete(analysis.id); const result = await shorts.renderContract(row.id); assert.equal(result.renderReady, false); assert.deepEqual(result.missingData, ['source video asset']); });
  test('Manager returns actual candidates and rationales', async () => { const row = await ready(); const registry = createDefaultCapabilityRegistry({ production, shorts }); const result = await registry.get('production.manage').execute({ request: { intent: 'acha os melhores Shorts desse video' }, results: new Map() }); assert.equal(result.data.productionId, row.id); assert.equal(result.data.candidates.length, 2); assert.ok(result.facts[0].includes('ms:')); });
  test('Production handler does not analyze generic research candidates or idea shortlists', async () => { await ready(); const registry = createDefaultCapabilityRegistry({ production, shorts }); for (const intent of ['gera candidatos de jogos', 'analisa candidato de pesquisa', 'shortlist de ideias']) await registry.get('production.manage').execute({ request: { intent }, results: new Map() }); assert.equal(await client.shortAnalysis.count(), 0); });
  test('Manager asks for source selection when multiple productions exist', async () => { await ready('one'); await ready('two'); const registry = createDefaultCapabilityRegistry({ production, shorts }); const result = await registry.get('production.manage').execute({ request: { intent: 'acha os melhores cortes' }, results: new Map() }); assert.deepEqual(result.missingData, ['production selection']); assert.equal(await client.shortAnalysis.count(), 0); });
  test('HTTP analyze list evidence select complete handoff and error contracts', async () => { const row = await ready(); let response = await request(`/productions/${row.id}/analyze`, 'POST', {}); assert.equal(response.status, 201); const analysis = response.body.analysis; assert.equal((await request(`/productions/${row.id}/analyze`, 'POST', {})).status, 200); assert.equal((await request(`/productions/${row.id}`)).body.length, 1); assert.equal((await request(`/candidates/${analysis.candidates[0].id}/evidence`)).body.segments.length, 3); assert.equal((await request(`/candidates/${analysis.candidates[0].id}/select`, 'POST', {})).status, 200); assert.equal((await request(`/analyses/${analysis.id}/complete`, 'POST', {})).status, 200); assert.equal((await request(`/productions/${row.id}/render-contract`)).status, 200); assert.equal((await request(`/productions/${row.id}/analyze`, 'POST', { secret: 'x' })).status, 400); const missing = await request('/analyses/missing'); assert.equal(missing.status, 404); assert.doesNotMatch(JSON.stringify(missing.body), /Prisma|stack|secret/); });
  test('migration enforces one current analysis and database integrity', async () => { const { analysis } = await generated(); await assert.rejects(() => client.shortAnalysis.create({ data: { productionId: analysis.productionId, transcriptId: analysis.transcriptId, version: 2, sourceFingerprint: 'new', configuration: {}, context: {}, limitations: [] } })); assert.equal((await client.$queryRawUnsafe('PRAGMA integrity_check'))[0].integrity_check, 'ok'); assert.deepEqual(await client.$queryRawUnsafe('PRAGMA foreign_key_check'), []); });
});
