import assert from 'node:assert/strict'; import { afterEach, test } from 'node:test';
import { createApiClient } from '../src/api/client.js'; import { createPackagingController, packagingModule } from '../src/modules/packaging.js';
class FakeElement { constructor(tag = 'div') { this.tagName = tag.toUpperCase(); this.map = new Map(); this.listeners = new Map(); this.attributes = new Map(); this.children = []; this.textContent = ''; this.className = ''; this.hidden = false; this.disabled = false; this.value = ''; this.dataset = {}; this.type = ''; }
  querySelector(selector) { if (this.map.has(selector)) return this.map.get(selector); const data = selector.match(/^\[data-([\w-]+)\]$/); if (!data) return null; const key = data[1].replace(/-([a-z])/g, (_, c) => c.toUpperCase()); const visit = (item) => item.children.find((child) => child.dataset?.[key] !== undefined) ?? item.children.map(visit).find(Boolean); return visit(this); }
  addEventListener(type, listener) { this.listeners.set(type, [...(this.listeners.get(type) ?? []), listener]); } removeEventListener(type, listener) { this.listeners.set(type, (this.listeners.get(type) ?? []).filter((item) => item !== listener)); }
  setAttribute(name, value) { this.attributes.set(name, String(value)); } append(...items) { this.children.push(...items); } replaceChildren(...items) { this.children = items; this.textContent = ''; }
  closest(selector) { const data = selector.match(/^\[data-([\w-]+)\]$/); if (!data) return null; const key = data[1].replace(/-([a-z])/g, (_, c) => c.toUpperCase()); return this.dataset[key] !== undefined ? this : null; }
  async dispatch(type, target = this) { await Promise.all((this.listeners.get(type) ?? []).map((listener) => listener({ target, preventDefault() {} }))); }
}
const originalDocument = globalThis.document; const originalFetch = globalThis.fetch; globalThis.document = { createElement: (tag) => new FakeElement(tag) };
afterEach(() => { globalThis.fetch = originalFetch; globalThis.document = { createElement: (tag) => new FakeElement(tag) }; }); process.on('exit', () => { globalThis.document = originalDocument; globalThis.fetch = originalFetch; });
const flush = () => new Promise((resolve) => setTimeout(resolve, 0)); const collect = (item) => `${item.textContent}${item.children.map(collect).join('')}`; const deferred = () => { let resolve; const promise = new Promise((ok) => { resolve = ok; }); return { promise, resolve }; };
const packaging = (id = 'p1', title = '<img src=x onerror=alert(1)>') => ({ id, game: 'City Car Driving 2.0', series: 'Vida de Motorista', status: 'DRAFT', summary: `Resumo ${id}`, history: [{ event: 'GENERATED', reason: null }], experiments: [], variants: [{ id: `v-${id}`, key: 'A', title, status: 'DRAFT', internalScore: .9, rationale: 'Evento real.', description: 'Descricao real.', tags: ['city car'], sourceEvent: 'carro quebrou', thumbnailBrief: { concept: '<script>alert(1)</script>', text: 'DEU PROBLEMA' }, metricSnapshots: [] }] });
const dom = () => { const root = new FakeElement(); const panel = new FakeElement(); root.map.set('.packaging-panel', panel); for (const selector of ['[data-packaging-form]', '[data-packaging-list]', '[data-packaging-detail]', '[data-packaging-feedback]']) panel.map.set(selector, new FakeElement()); panel.map.get('[data-packaging-form]').map.set('[data-packaging-generate]', new FakeElement('button')); return { root, get: (selector) => panel.querySelector(selector) }; };

test('central API client exposes every packaging contract with ids only in paths', async () => { const calls = []; globalThis.fetch = async (url, options = {}) => { calls.push([String(url), options]); return { ok: true, status: options.method === 'POST' ? 201 : 200, json: async () => ({}) }; }; const api = createApiClient('http://localhost:3000'); await api.listPackagings({ game: 'Forza', limit: 5 }); await api.generatePackaging({ summary: 'x' }); await api.getPackaging('p/1'); await api.getPackagingHistory('p/1'); await api.editPackagingVariant('v/1', { title: 'x' }); await api.selectPackagingVariant('v/1'); await api.rejectPackagingVariant('v/1'); await api.publishPackagingVariant('v/1', { videoId: 'youtube' }); await api.observePackagingVariant('v/1'); await api.reviewPackagingVariant('v/1'); await api.createPackagingExperiment('p/1', { hypothesis: 'x', variantIds: ['a', 'b'] }); await api.recordPackagingLearning('p/1'); assert.equal(calls.length, 12); assert.match(calls[2][0], /p%2F1/); assert.equal(calls[5][1].body, '{}'); await assert.rejects(() => api.getPackaging(' '), TypeError); });
test('workspace is fullscreen and loads persisted packaging history once', async () => { assert.equal(packagingModule.fullscreen, true); assert.match(packagingModule.render(), /data-packaging-form/); const page = dom(); let calls = 0; const controller = createPackagingController({ api: { listPackagings: async () => { calls += 1; return [packaging()]; } } }); controller.mount(page.root); controller.mount(page.root); await flush(); assert.equal(calls, 1); assert.equal(page.get('[data-packaging-list]').children.length, 1); });
test('opening a variant renders untrusted title and thumbnail as literal text', async () => { const page = dom(); const controller = createPackagingController({ api: { listPackagings: async () => [packaging()], getPackaging: async () => packaging() } }); controller.mount(page.root); await flush(); await page.get('[data-packaging-list]').dispatch('click', page.get('[data-packaging-list]').children[0]); await flush(); assert.match(collect(page.get('[data-packaging-detail]')), /<img src=x onerror=alert\(1\)>/); assert.match(collect(page.get('[data-packaging-detail]')), /<script>alert\(1\)<\/script>/); });
test('late detail cannot replace a newer packaging and unmount ignores responses', async () => { const first = deferred(); const page = dom(); const controller = createPackagingController({ api: { listPackagings: async () => [packaging('a'), packaging('b')], getPackaging: async (id) => id === 'a' ? first.promise : packaging('b', 'Titulo B') } }); controller.mount(page.root); await flush(); const rows = page.get('[data-packaging-list]').children; const pending = page.get('[data-packaging-list]').dispatch('click', rows[0]); await page.get('[data-packaging-list]').dispatch('click', rows[1]); first.resolve(packaging('a', 'Titulo A')); await pending; assert.match(collect(page.get('[data-packaging-detail]')), /Titulo B/); controller.unmount(); });
test('list failure stays local and creates no false packaging', async () => { const page = dom(); createPackagingController({ api: { listPackagings: async () => { throw new Error('secret'); } } }).mount(page.root); await flush(); assert.equal(page.get('[data-packaging-list]').children.length, 0); assert.match(page.get('[data-packaging-feedback]').textContent, /Nao foi possivel/); assert.doesNotMatch(page.get('[data-packaging-feedback]').textContent, /secret/); });
